- resources/views/events/show.blade.php
Adds enquete button in the events view for Members (admins and non-admins) . Fixed #2.
@robinklaassen Ik moest een beetje gokken wat de bedoeling was, maar met de hulp van @IrisvM  is dit em geworden.
> added druif enquete

- app/Http/Controllers/PagesController.php
- resources/views/pages/lists.blade.php
Deze zag ik net nog in mijn aantekeningen staan (naar aanleiding van een brainstormavond over de promotie), dus even toegevoegd. Het gemiddeld aantal dagen tussen de inschrijving van een deelnemer voor een kamp en de startdatum van dat kamp. Niet spannend, wel nuttig.
> Klein statistiekje

- app/Http/Controllers/RegistrationController.php
> fixed missing privacy field on registration

- app/Http/Controllers/EventsController.php
- routes/web.admin.php
- routes/web.member.php
- routes/web.php
Fixed #55 
Er is wel een kans dat andere routes breken, ik heb al wat er door heen geklikt en zag niets.
> Reordered routes, fixed #55

- app/Http/Controllers/PasswordController.php
- app/Http/Controllers/RegistrationController.php
- app/Http/Controllers/UsersController.php
- app/User.php
- tests/Unit/PasswordTest.php
Closes #60 
Changed password generation to a single class (static in app/User) .
Excludes look alike characters: O 0 o, i I L l, V v W w, s S 5.
> Changed password generation

- app/Http/Controllers/PagesController.php
- resources/views/pages/lists.blade.php
Klein verzoekje van Bouchien vanmiddag, ik dacht ik implementeer 'm gelijk even. Voegt het gemiddelde cijfer uit de enquêtes toe aan de lijsten.
Lijkt een lange PR maar dat komt door die Intelephense auto-formatter 🙈
> Add average review score to lists

- app/Http/Controllers/PagesController.php
- resources/views/pages/lists.blade.php
Closes #59
Voegt tabje in lijsten toe voor oud leden
Maakt alle emails net iets makkelijker te kopiëren dmv een knop.
> Oud leden lijst #59

- resources/views/actions/index.blade.php
Gemeld door Kevin, dacht ik fix 'm gelijk even :)
> Fix: typo in create Action

- .travis.yml
- composer.json
upgraded phpspec to make it compatible with php7.4
changed travis php version to 7.4
> Made AAS2 PHP7.4 compatible.

- public/css/custom.css
> Turn that frown upside down

- app/Role.php
- app/User.php
- app/UserRole.php
- resources/views/members/index.blade.php
- resources/views/members/show.blade.php
> show roles in members index

- app/Participant.php
- resources/views/events/show.blade.php
> Hotfix: bad level column in events.show participant table

- app/Http/Controllers/PagesController.php
- resources/views/partials/nav.blade.php
Closes #95
Removed rights check on graphs.
these graphs are anonymous and nice for every member.
> Removed rights on graphs page

- deploy_prd.sh
Fixed deploy script to use the composer lock file instead of creating a new one
> changed composer update to install in deploy script

- .env.example
- .env.travis
- resources/views/emails/participants/onEventConfirmation.blade.php
- tests/Unit/Mails/ParticipantOnEventConfirmationTest.php
Work in progress
Tests voor Mailable classes.
Closes #93
> Mailable unit tests

- app/Policies/ParticipantPolicy.php
- database/migrations/2020_07_28_110501_add_password_right_to_kantoorci.php
- resources/views/participants/show.blade.php
Closes #108 
- Gave kantoorci participants::info::edit::password rights
- Fixed participant policy to check on participants::info::edit::password
- Added changepassword button to show page of participants
> Gave kantoorci the ability to change participant passwords again.

- resources/views/members/form.blade.php
- resources/views/members/show.blade.php
Closes #110 
Fixed typo in permissions
> Fixed permissions for account number

- app/Http/Controllers/PagesController.php
- resources/views/pages/graphs.blade.php
Implementatie is quick en dirty net zoals de rest van die graphs, vooral in de PagesController graph() method. Ben wel voor om die nog eens goed te refactoren. Maar voor nu doet dit het en worden we weer blij van een nieuw grafiekje :)
> Added graph for average number of members/participants per camp

- .travis.yml
- deployment/deploy.partial.sh
- resources/views/declarations/index.blade.php
- resources/views/partials/nav.blade.php
Hide the declarations navigation.
Added alert to the new declarations with an link to the current one.
> Hide declaration button & post deploy cleanup

- resources/views/declarations/index.blade.php
- resources/views/members/show.blade.php
- resources/views/partials/nav.blade.php
David was like: nice. 
So I was like: Let's go.
> Declarations go live

- app/Http/Controllers/MembersController.php
- composer.lock
- resources/views/members/index.blade.php
- resources/views/members/search.blade.php
- resources/views/members/searchSkills.blade.php
- resources/views/members/show.blade.php
- routes/web.auth.php
Eerste versie, technisch werkt het maar ik moet nog wat met de CSS spelen om de pagina netter te maken. Maar een eerste review is al welkom als je tijd hebt :)
> Feature: skill search form

- app/Http/Controllers/PagesController.php
- resources/views/pages/graphs.blade.php
Requested by Fieke.
Add how many people found anderwijs by which source
> Added chart for new users by source

- app/Http/Controllers/EventsController.php
- app/Http/Controllers/PagesController.php
- app/Http/Controllers/ParticipantsController.php
- app/Policies/MemberPolicy.php
- app/Policies/ParticipantPolicy.php
- resources/views/events/email.blade.php
- resources/views/events/show.blade.php
- resources/views/pages/home-member.blade.php
> Fixes all issues raised by iris / kantoorci

- resources/views/pages/graphs.blade.php
Camp prices graph shows an error (fixed remotely while debugging, this fixes it)
> Fixed camp price data type error

- resources/views/events/show.blade.php
Zoals gemeld door Liesbeth vanochtend via de mail.
> Fix error when participant has no package on event

- app/Http/Controllers/EventsController.php
Uit de mail van Marije begreep ik dat vakdekkingschecker niet werkte voor online events, was gauw gevonden.
> coverage can be for camp or online event

- app/Services/Anonymize/AnonymizeParticipant.php
Fix anonymization based on last event instead of any event.
Keep 'some' information like niveau and hoebij
> Fix anonymization based on last event instead of any event.

- app/Participant.php
- deployment/deploy.partial.sh
- resources/views/profile/onCamp.blade.php
- resources/views/registration/participant.blade.php
- Added default value for selected package
- Added previously selected value
- use /register-participant to register. 
- Check the selected package has an default value which is invalid
- Pick a `selected_package`, forget something else, submit, see error and observe the value is selected again
> Default selected packages during registration

- app/Http/Controllers/PagesController.php
Ik kwam er achter dat er nu bij het Online Lentekamp de tekst "Prijs: Wordt nog vastgesteld" stond, terwijl het in AAS2 als 0 stond (niet null). Deze fix fixed dat. 
Ik heb ervoor gekozen om de prijs dan helemaal weg te halen om zo verwarring te voorkomen, gezien we ook pakketten hebben is het dan niet echt gratis te noemen.
> Fix for not displaying price when there isn't any

- app/Http/Middleware/CheckForMaintenanceMode.php
Zorgt ervoor dat de updater routes (version & update) beschikbaar blijven als de app in maintenance mode is.
> added updater routes to maintenance exception

- .github/workflows/ci.yml
Fixes for our github actions workflow
- removed php 7.3 from test matrix
- remove debug step for assets
- add longer timeout and empty response ok to http deploy action
> fix and cleanup github action yaml

- resources/views/emails/members/newUserMember.blade.php
- resources/views/emails/members/registrationConfirmation.blade.php
- resources/views/emails/participants/iDealConfirmation.blade.php
- resources/views/emails/participants/newUserParticipant.blade.php
- resources/views/emails/participants/onEventConfirmation.blade.php
- resources/views/emails/participants/registrationConfirmation.blade.php
> Update emails met goede website links

- tests/Feature/MemberRegistrationTest.php
Dit was mijn lokale probleem, kon geen verbinding krijgen met de opgegeven mailserver.
> Mail::fake() toevoegen aan test

- package.json
Fix in yarn production  command due to laravel-mix upgrade
> Quick fix after dependency upgrade

- app/Http/Controllers/PagesController.php
Nav appje van Fieke in de actieve leden app.
> filter old members from ranonkeltje lists

- app/Comment.php
- resources/views/events/export.blade.php
Fixes #190 
- Add non-secret comments to export
- Cleaned up styling in export
- Fixed front-page
> Fix participant export

- resources/markdown/privacy-statement.md
> Update privacy statement of hosting provider to antagonist

- app/Services/Anonymize/AnonymizeParticipant.php
> Use first event for anonymisation instead of last

- package.json
- yarn.lock
Ik zag dat we wat veel security issues hebben in de node dependencies, dus dit is een eerste poging om dat aan te pakken. Het fixt niet alles maar wel een deel en het kostte weinig tijd :)
Denk dat we er nog wel een keer dieper op in moeten gaan.
> Added and used package yarn-audit-fix

- app/Declaration.php
- app/Http/Controllers/DeclarationsController.php
- app/Http/Requests/BulkDeclarationsRequest.php
- database/migrations/2021_09_28_201922_add_declaration_bio_meat_gift.php
- resources/js/components/declarations/DeclarationInputRow.vue
- resources/js/components/declarations/DeclarationsForm.vue
- resources/js/components/declarations/data/DeclarationRow.ts
- resources/lang/nl/declaration-types.php
- resources/views/declarations/admin.blade.php
- resources/views/declarations/form.blade.php
- resources/views/declarations/index.blade.php
- resources/views/declarations/process.blade.php
- routes/web.auth.php
- Altered gift to include payout to biomeat
- Split confirmation based on type
- Add declarations with various types
- Use the Treasurer dashboard to process them.
> Add biomeat gift option, reworked gifting into an option

- app/Http/Controllers/MembersController.php
- app/Http/Controllers/ParticipantsController.php
- app/Http/Controllers/ProfileController.php
- tests/Feature/MemberProfileTest.php
> fix roles screwup when updating profile

- composer.json
- composer.lock
Fixes bad layout in camp exports
> Update pdf dependency

- app/Helpers/Payment/Donation.php
- app/Helpers/Payment/EventPayment.php
- app/Helpers/Payment/MolliePaymentProvider.php
- app/Helpers/Payment/PaymentInterface.php
- app/Http/Controllers/DonateController.php
- app/Http/Controllers/iDealController.php
- app/Http/Requests/DonationRequest.php
- app/Providers/MollieServiceProvider.php
- config/app.php
- resources/views/pages/donation-response.blade.php
- resources/views/pages/iDealResponse.blade.php
- resources/views/registration/iDealResponse.blade.php
- routes/web.public.php
- tests/Feature/IDealResponseTest.php
- tests/Unit/Helpers/Payment/DonationTest.php
- tests/Unit/Helpers/Payment/EventPaymentTest.php
- tests/Unit/Helpers/Payment/MolliePaymentProviderTest.php
- Use a browser and go to [aas2.local/donate?amount=10.00&name=test](http://aas2.local/doneer?amount=10.00&name=test)
- See it redirects to mollie and all
- Register a new participant and pay with ideal
- The webhook will not work locally so every payment "fails"
- You can test the webhook by getting the payment id from mollies dashboard or adding a `dd(Mollie::api()->payments->page());` in somewhere on the iDealController and use the first id you see (which will be the newest).
> Add donate controller and functionality to mollie

- app/Http/Controllers/PagesController.php
- app/Models/Event.php
- app/Models/Member.php
- resources/js/app.ts
- resources/js/components/CampThermometer/CampThermometerBar.vue
- resources/views/pages/home-member.blade.php
Closes #231 
Bit of scope creep, also refactored the birthday list for members since it's on same page/controller.
> Camp thermometer refactor

- app/Exceptions/MethodNotAllowedException.php
- app/Models/Event.php
- database/seeders/EventTableSeeder.php
- ecs.php
- resources/views/events/show.blade.php
- resources/views/pages/home-member.blade.php
- tests/Feature/EventTest.php
> Trainingen toevoegen aan kamp thermometer

- app/Helpers/Payment/EventPayment.php
- app/Http/Controllers/PagesController.php
- app/Http/Controllers/ProfileController.php
- app/Pivots/EventParticipant.php
- database/seeders/EventTableSeeder.php
- database/seeders/ParticipantTableSeeder.php
- resources/views/pages/home-participant.blade.php
- routes/web.auth.php
- tests/Feature/ParticipantHomeTest.php
> Status inschrijving op deelnemer homepage

- app/Http/Controllers/EventsController.php
- app/Models/Course.php
- resources/views/events/check.blade.php
> Restyle vakdekkingschecker

- resources/js/components/CampThermometer/CampThermometerBar.vue
> camp thermometer partial bar percentage limit fixed

- app/Http/Controllers/RegistrationController.php
- resources/views/registration/member.blade.php
- resources/views/registration/memberStored.blade.php
- resources/views/registration/participant.blade.php
- resources/views/registration/participantStored.blade.php
Was working on fixing event titles and statuses, but saw a lot of dead links on the registration pages, so let's just fix those first and I'll do other stuff later.
> Cleanup & fix registration pages

- app/Policies/EventPolicy.php
- app/Services/Chart/LavachartsChartService.php
- routes/web.auth.php
- fixes visibility of general event reviews for attending members
- ensures axis ticks on bar charts are integer
> fix review visibility and axis tick rounding

- app/Http/Controllers/EventsController.php
- composer.json
- composer.lock
- config/app.php
- yarn.lock
This should fix all the current vulnerabilities.
I upgrade the dompdf package to 2.0 for a fix as well, but haven't tested every pdf manually. If you'd like... or just see who cares :)
> update composer and yarn deps

- app/Helpers/Payment/EventPayment.php
- app/Http/Controllers/ApiController.php
- app/Http/Requests/EventRequest.php
- app/Models/Event.php
- app/Models/Participant.php
- database/migrations/2022_11_26_173512_add_early_bird_discount_to_events.php
- resources/views/events/form.blade.php
- resources/views/events/show.blade.php
- tests/Feature/EventTest.php
- tests/Feature/PublicJSONApiTest.php
- tests/Unit/Helpers/Payment/EventPaymentTest.php
- tests/Unit/Models/EventTest.php
Closes #282
- Je kan vroegboek korting op een event toepassen
- Deze wordt ook weergegeven
- De vroegboek korting wordt ook weergegeven in de public api
> Vroegboek korting

- app/Http/Controllers/ApiController.php
One of the prices was nested one to deep
> Fix nested price api bug

- composer.lock
- resources/views/reviews/form.blade.php
- yarn.lock
Closes #290 
Enige pronouns die ik nog kon vinden zaten in de deelnemerenquête. Heb ook gelijk composer en yarn geüpdatet gezien alle dependabot PR's.
> Cleanup pronouns

- resources/sass/app.sass
... You spin me right 'round, baby, right 'round
Like a record, baby, right 'round, 'round, 'round
You spin me right 'round, baby, right 'round
Like a record, baby, right 'round, 'round, 'round
> Like a Record

- resources/sass/app.sass
Reverts robinklaassen/aas2#360
Was weer een mooie 1 april
> Revert "Like a Record"

- packages/Updater/Services/Updater/UpdaterService.php
Should fix the deploy problems, according to https://divinglaravel.com/the-problem-behind-undefined-constant-stdin-when-running-laravel-artisan-command-programmatically
> Force artisan commands in UpdaterService

- packages/Updater/Listeners/ArtisanPostUpdateListener.php
- packages/Updater/Listeners/ArtisanPreUpdateListener.php
Since last PR did not fix the problem
> force more artisan commands

- routes/web.guest.php
- tests/Feature/MemberRegistrationTest.php
- tests/Feature/ParticipantRegistrationTest.php
No more Anderwijs :(  disables registration of new members and participants by removing the routes.
> Disable registration
